- AdminNoticeDetailPage/View/AdminNoticeDetailView.swift
- AdminNoticeDetailPage/ViewController/AdminNoticeDetailViewController.swift
- AdminNoticePage/View/AdminNoticeTableViewCell.swift
- AdminNoticePage/View/AdminNoticeView.swift
- AdminNoticePage/ViewController/AdminNoticeViewController.swift
- AdminRootPage/View/AdminRootView.swift
- AdminRootPage/ViewController/AdminRootViewController.swift
- GYMGLE.xcodeproj/project.pbxproj
- GYMGLE/Application/SceneDelegate.swift
- GYMGLE/Extension/Extension_UIButton.swift
- GYMGLE/Extension/Extension_UILabel.swift
- GYMGLE/Helpers/ColorGuide.swift
[FEAT] : ⚙️ seongwon / 공지사항 리스트 화면 모두 구현
> [MERGE] : ✅ swongwon / 1차 병합

- GYMGLE.xcodeproj/project.pbxproj
- GYMGLE/Application/SceneDelegate.swift
- GYMGLE/Model/DataManager.swift
- GYMGLE/Pages/User/UserManagePage/View/Components/ManageTableView.swift
- GYMGLE/Pages/User/UserManagePage/View/UserManageView.swift
- GYMGLE/Pages/User/UserManagePage/ViewContoller/UserManageController.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/TextFieldCell.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
> [FEAT] : ⚙️ | 공성표 | 유저 리스트 테이블뷰에 표시, 유저 리스트에 추가

- GYMGLE.xcodeproj/project.pbxproj
- GYMGLE/Model/DataManager.swift
- GYMGLE/Model/DataTestViewController.swift
- GYMGLE/Pages/User/UserManagePage/ViewContoller/UserManageController.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/PopUp/PopUpView.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/TextFieldCell.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewIDPWController.swift
[MERGE] : ✅ 공성표 | 회원등록 두개로 분할, 버튼 비활성화, ID 유효성 검사 구현
> [MERGE] : ✅ 공성표 | 회원등록 두개로 분할, 버튼 비활성화, ID 유효성 검사 구현 후 병합

- GYMGLE/Pages/Admin/AdminLoginPage/View/AdminLoginView.swift
- GYMGLE/Pages/Admin/AdminLoginPage/ViewController/AdminLoginViewController.swift
- GYMGLE/Pages/Admin/AdminRegisterPage/View/AdminRegisterView.swift
- GYMGLE/Pages/Admin/AdminRegisterPage/ViewController/AdminRegisterViewController.swift
- GYMGLE/Pages/Admin/QRcodeCheckPage/ViewController/QRcodeCheckViewController.swift
- GYMGLE/Pages/InitialViewPage/View/InitialView.swift
- GYMGLE/Pages/InitialViewPage/ViewController/InitialViewController.swift
> [MERGE] : ✅  seongwon / 더미데이터 5차 병합

- GYMGLE/Application/AppDelegate.swift
- GYMGLE/Application/SceneDelegate.swift
- GYMGLE/Extension/Extension_CALayer.swift
- GYMGLE/Pages/User/UserManagePage/View/Components/ManageLabelCell.swift
- GYMGLE/Pages/User/UserManagePage/View/Components/ManageTableView.swift
- GYMGLE/Pages/User/UserManagePage/ViewContoller/UserManageController.swift
- GYMGLE/Pages/User/UserRegisterPage/View/UserRegisterView.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewIDPWController.swift
- GYMGLE/ViewController.swift
[FEAT] : ⚙️ 공성표 / 회원등록뷰에서 트레이너 전용 회원용 세그멘티드 컨트롤 추가, 등록시 type 2 로 추가되는 로직
> [FEAT] : ⚙️ 공성표 / 회원등록뷰에서 트레이너 전용 회원용 세그멘티드 컨트롤 추가, 등록시 type 2 로 추가되는 로직

- GYMGLE/Pages/User/UserManagePage/ViewContoller/UserManageController.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewIDPWController.swift
[MERGE] : ✅ 공성표 / CRUD 구현, 가입 이메일 등록처리 오류 수정
> [MERGE] : ✅ 공성표 / CRUD 구현, 가입 이메일 등록처리 오류 수정

- GYMGLE/Pages/User/UserManagePage/ViewContoller/UserManageController.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewIDPWController.swift
[FIX] : 🐛 공성표 / gymUserList 제거, accounts 로 통합
> [FIX] : 🐛 공성표 / gymUserList 제거, accounts 로 통합

- GYMGLE/Pages/Admin/AdminRegisterPage/ViewController/AdminRegisterViewController.swift
[FIX] : 🐛 공성표 / gymUserList 삭제
> [MERGE] : 🐛 공성표 / gymUserList 삭제

- GYMGLE/Pages/User/UserRootPage/UserRootViewController.swift
> [MERGE] : ✅ 김기호 / 병합

- GYMGLE.xcodeproj/project.pbxproj
- GYMGLE/Pages/User/UserRegisterPage/View/Components/PopUp/BottomSheetController.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/PopUp/BottomSheetView.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/PopUp/BottomSheetViewDateOnly.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
[DESIGN,FIX] : 🎨 공성표 / 팝업뷰 -> 바텀시트뷰
> [DESIGN,FIX] : 🎨 공성표 / 팝업뷰 -> 바텀시트뷰

- GYMGLE.xcodeproj/project.pbxproj
- GYMGLE/Pages/User/UserRegisterPage/View/Components/PopUp/BottomSheetController.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/PopUp/BottomSheetView.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/PopUp/BottomSheetViewDateOnly.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/PopUp/CustomButton.swift
- GYMGLE/Pages/User/UserRegisterPage/View/UserRegisterView.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewIDPWController.swift
[DESIGN] : 🎨 공성표 / 회원등록뷰 타이틀레이블 삭제, 날짜선택 제한추가
> [DESIGN] : 🎨 공성표 / 회원등록뷰 타이틀레이블 삭제, 날짜선택 제한추가

- GYMGLE/Pages/User/UserMyPage/View/MyPageTableView.swift
- GYMGLE/Pages/User/UserMyPage/View/UserMyPageView.swift
- GYMGLE/Pages/User/UserRootPage/UserRootView.swift
- GYMGLE/Pages/User/UserRootPage/UserRootViewController.swift
[DESIGN] : 🎨    김기호    /   디자인 변경
> 		[DESIGN] : 🎨    김기호    /   디자인 변경         

- GYMGLE.xcodeproj/project.pbxproj
- GYMGLE/Application/SceneDelegate.swift
- GYMGLE/Pages/User/UserBoardDetailPage/View/BoardDetailView.swift
- GYMGLE/Pages/User/UserBoardDetailPage/View/Components/BoardDetailCommentCell.swift
- GYMGLE/Pages/User/UserBoardDetailPage/View/Components/BoardDetailCommentSection.swift
- GYMGLE/Pages/User/UserBoardDetailPage/View/Components/BoardDetailContentCell.swift
- GYMGLE/Pages/User/UserBoardDetailPage/View/Components/BoardDetailTableView.swift
- GYMGLE/Pages/User/UserBoardDetailPage/View/Components/BoardProfileMini.swift
- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/LabelCell.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/UserTableView.swift
- GYMGLE/Pages/User/UserRegisterPage/View/UserRegisterView.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewIDPWController.swift
- GYMGLE/TabbarViewController.swift
[DESIGN] : 🎨 공성표 / 게시글디테일페이지 UI작업 완료
> [MERGE] : ✅ 공성표 / 게시글디테일페이지 UI작업 완료 후 병합

- GYMGLE/Pages/User/UserCommunityPage/CommunityCell.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteViewController.swift
- GYMGLE/TabbarViewController.swift
[DESIGN] : 🎨 김기호 / communitiy디자인 변경
> [DESIGN] : 🎨 김기호 / communitiy디자인 변경

- GYMGLE/Helpers/Protocol_Delegate.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityViewController.swift
[FEAT] : ⚙️ 김기호 / 게시글 detailPage로 넘어가는것 구현
> [FEAT] : ⚙️ 김기호 / 게시글 detailPage로 넘어가는것 구현

- GYMGLE/Pages/User/UserCommunityPage/CommunityCell.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteViewController.swift
[FEAT] : ⚙️ 김기호 / 게시글작성시 테이블뷰에서 Read 하는 기능 하는중
> [FEAT] : ⚙️ 김기호 / 게시글작성시 테이블뷰에서 Read 하는 기능 하는중

- GYMGLE/Model/Board.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteViewController.swift
- GYMGLE/ReportViewController.swift
[FEAT] : ⚙️ 김기호 /프로필 추가 기능 수정중
> [FEAT] : ⚙️ 김기호 /프로필 추가 기능 수정중

- GYMGLE/Pages/User/UserCommunityPage/UserCommunityView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteViewController.swift
> [FIX] : 🐛 김기호 / 버그 수정

- GYMGLE/Pages/User/UserBoardDetailPage/View/BoardDetailView.swift
- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
> [HOTFIX] : 💥 공성표 / Profile 추가

- GYMGLE/Pages/User/UserCommunityPage/UserCommunityView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteViewController.swift
[FIX] : 🐛 김기호 / 프로필 파이어베이스 > 싱글톤에서 받는것으로 수정
> [FIX] : 🐛 김기호 / 프로필 파이어베이스 > 싱글톤에서 받는것으로 수정

- GYMGLE/Pages/User/UserBoardDetailPage/View/BoardDetailView.swift
- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityViewController.swift
[FIX] : 🐛 공성표 / 커뮤니티뷰 셀에서 보드 받아와 화면출력
> [FIX] : 🐛 공성표 / 커뮤니티뷰 셀에서 보드 받아와 화면출력

- GYMGLE/Pages/User/UserBoardDetailPage/View/Components/BoardProfileLine.swift
- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityView.swift
[FIX] : 🐛 공성표 / 커뮤니티탭에서 키값 잘못받아오는 버그 수정
> [FIX] : 🐛 공성표 / 커뮤니티탭에서 키값 잘못받아오는 버그 수정

- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
[[FEAT] : ⚙️ 공성표 / 프로필 어카운트에서 불러오기](https://github.com/team-Sparta-Final-Project/GYMGLE/commit/ce20ef0d37fb53336cdff7e1899e78446ba03827)
> [MERGE] : ⚙️ 공성표 / 프로필 어카운트 참조 병합

- GYMGLE/Pages/User/UserBoardDetailPage/View/Components/BoardProfileLine.swift
- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityViewController.swift
[FIX] : 🐛 공성표 / 프로필 눌렀을 때 최상단 유저 프로필만 뜨는 버그 수정
> [FIX] : 🐛 공성표 / 프로필 눌렀을 때 최상단 유저 프로필만 뜨는 버그 수정

- GYMGLE/BlockViewController.swift
- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteViewController.swift
- GYMGLE/ReportViewController.swift
> [MERGE] : ⚙️ 공성표 / 수정기능, 신고기능

- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteViewController.swift
> [FIX] : 🐛 김기호 / 버그수정 글안서지는거

- GYMGLE/Pages/User/UserCommunityPage/UserCommunityViewController.swift
[HOTFIX] : 💥 공성표 / 인덱스 에러 수정
> [HOTFIX] : 💥 공성표 / 인덱스 에러 수정

- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/CommunityCell.swift
> [MERGE] : ✅ 김기호 / 댓글갯수받아오기 수정

- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityWriteViewController.swift
[HOTFIX] : 💥 공성표 / observe가 여러번 중첩되어 실행되는 버그 해결
> [HOTFIX] : 💥 공성표 / observe가 여러번 중첩되어 실행되는 버그 해결

- GYMGLE/Pages/User/UserRootPage/UserRootView.swift
[FEAT] : ⚙️ 김기호 / 공지 글 문단따라서 달라지기 수정
> [FEAT] : ⚙️ 김기호 / 공지 글 문단따라서 달라지기 수정

- GYMGLE/Pages/User/UserBoardDetailPage/View/Components/BoardDetailContentCell.swift
- GYMGLE/Pages/User/UserBoardDetailPage/View/Components/BoardProfileLine.swift
- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityViewController.swift
- GYMGLE/Pages/User/UserManagePage/View/Components/ManageLabelCell.swift
- GYMGLE/Pages/User/UserManagePage/ViewContoller/UserManageController.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/UserTableView.swift
- GYMGLE/Pages/User/UserRegisterPage/View/UserRegisterView.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
[FIX] : 🐛 공성표 / 커뮤니티 검색기능 fix, 성별 제거
> [FIX] : 🐛 공성표 / 커뮤니티 검색기능 fix, 성별 제거

- GYMGLE/Pages/User/UserCommunityPage/UserCommunityView.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityViewController.swift
[HOTFIX] : 💥 공성표 / 검색기능에서 프로필 검색 버그
> [HOTFIX] : 💥 공성표 / 검색기능에서 프로필 검색 버그

- GYMGLE/Application/AppDelegate.swift
- GYMGLE/Pages/Admin/AdminNoticePage/View/AdminNoticeTableViewCell.swift
- GYMGLE/Pages/Admin/AdminNoticePage/View/AdminNoticeView.swift
- GYMGLE/Pages/Admin/AdminNoticePage/ViewController/AdminNoticeViewController.swift
[DESIGN] : 🎨 김기호 / adminNoticeView 디자인 수정
> [DESIGN] : 🎨 김기호 / adminNoticeView 디자인 수정

- GYMGLE/Assets.xcassets/AppIcon.appiconset/Contents.json
- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
- GYMGLE/Pages/User/UserCommunityPage/UserCommunityViewController.swift
> [FEAT] : ⚙️ 공성표 / 탈퇴회원 기본값 처리

- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
[HOTFIX] : 💥 공성표 / 탈퇴한 게시글 댓글 비활성화
> [HOTFIX] : 💥 공성표 / 탈퇴한 게시글 댓글 비활성화

- GYMGLE/Pages/User/UserRegisterPage/View/Components/CustomTextCell.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/UserTableView.swift
- GYMGLE/Pages/User/UserRegisterPage/View/UserRegisterView.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
[DESIGN] : 🎨 공성표 / 등록뷰 레이아웃 se3 대응 겸 키보드 반응형 버튼
> [DESIGN] : 🎨 공성표 / 등록뷰 레이아웃 se3 대응 겸 키보드 반응형 버튼

- GYMGLE/Pages/Admin/AdminRegisterPage/ViewController/AdminRegisterViewController.swift
- GYMGLE/Pages/User/UserRootPage/UserRootView.swift
> [MERGE] : ✅ 김기호 / 앱배포 최최종병합

- GYMGLE.xcodeproj/project.pbxproj
> [MERGE] : ✅ 김기호 / 앱배포 최최최종

- GYMGLE/Pages/User/UserBoardDetailPage/ViewController/BoardDetailViewController.swift
- GYMGLE/Pages/User/UserRegisterPage/View/Components/UserTableView.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewController.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewIDPWController.swift
[HOTFIX] : 💥 공성표 / 프로필 생성 전 댓글 기능 제한, 상세정보
> [HOTFIX] : 💥 공성표 / 프로필 생성 전 댓글 기능 제한, 상세정보

- GYMGLE/Pages/User/UserRootPage/UserRootModel.swift
- GYMGLE/Pages/User/UserRootPage/UserRootView.swift
[REFACTOR] : ♻️ 김기호/     MVVM 진행중
> [REFACTOR] : ♻️ 김기호/     MVVM 진행중

- GYMGLE/Application/EmailSender.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserEmailVerified.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserEmailViewController.swift
> smtp작업중 테스트

- GYMGLE.xcodeproj/project.pbxproj
- GYMGLE.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- GYMGLE/Application/EmailSender.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserEmailVerified.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserEmailViewController.swift
- GYMGLE/Pages/User/UserRegisterPage/ViewController/UserRegisterViewIDPWController.swift
> smtp 작업 테스트
